src/SimpleBlog/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimpleBlog.Services;
using SimpleBlog.ViewModels;
using System.Threading.Tasks;

namespace SimpleBlog.Controllers
{
    [Route("c")]
    public class CategoryController : Controller
    {
        private readonly CategoryService _categoryService;
        private readonly PostController _postController;

        public CategoryController(CategoryService categoryService, PostController postController)
        {
            _categoryService = categoryService;
            _postController = postController;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var categories = await _categoryService.List();
            return View(new CategoryListViewModel { Categories = categories });
        }

        [HttpGet("{slug}")]
        public async Task<IActionResult> PostList(string slug, [FromQuery(Name = "p")]int page = 1)
        {
            var category = await _categoryService.GetBySlug(slug);
            return await _postController.List(p => p.CategoryId == category.Id, page, category.Name);
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost("new")]
        [HttpPost("edit/{id}")]
        public async Task<IActionResult> CreateOrUpdate(CategoryListViewModel viewModel, int? id)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Categories = await _categoryService.List();
                return View("Index", viewModel);
            }

            var category = viewModel.Category;
            if (id == null)
            {
                await _categoryService.Create(category);
            }
            else
            {
                category.Id = id.Value;
                await _categoryService.Update(category);
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost("[action]/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await _categoryService.GetById(id);
            await _categoryService.Delete(category);

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpGet("[action]/{id}")]
        public async Task<IActionResult> CanBeDelete(int id)
        {
            var result = await _categoryService.CanBeDelete(id);
            return Ok(result);
        }
    }
}

src/SimpleBlog/Controllers/PostController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SimpleBlog.Infrastructures.GuardClauses;
using SimpleBlog.Models;
using SimpleBlog.Services;
using SimpleBlog.ViewModels;
using System;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace SimpleBlog.Controllers
{
    [Route("p")]
    public class PostController : Controller
    {
        private readonly PostService _postService;
        private readonly TagService _tagService;
        private readonly IMapper _mapper;
        private readonly UserManager<User> _userManager;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public PostController(
            PostService postService,
            TagService tagService,
            IMapper mapper,
            UserManager<User> userManager,
            IHttpContextAccessor httpContextAccessor)
        {
            _postService = postService;
            _tagService = tagService;
            _mapper = mapper;
            _userManager = userManager;
            _httpContextAccessor = httpContextAccessor;
        }

        [HttpGet("/")]
        public Task<IActionResult> Index([FromQuery(Name = "p")]int page = 1)
        {
            return List(_ => true, page, null);
        }

        [HttpGet("{slug}")]
        public async Task<IActionResult> Article(string slug)
        {
            var post = await _postService.GetBySlug(slug);
            var viewModel = new PostViewModel { Post = post };

            if (post.IsDraft)
                return RedirectToAction(nameof(Edit), new { post.Id });
            return View(viewModel);
        }

        [Authorize]
        [HttpGet("[action]")]
        public IActionResult New()
        {
            var model = new PostInputModel
            {
                IsDraft = true
            };

            return View("Edit", model);
        }

        [Authorize]
        [HttpGet("[action]/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            var post = await _postService.GetById(id);

            return View(_mapper.Map<PostInputModel>(post));
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost("new")]
        [HttpPost("edit/{id}")]
        public async Task<IActionResult> CreateOrUpdate(PostInputModel model, int? id)
        {
            if (!ModelState.IsValid)
                return View("Edit", model);

            Post post;
            var tagList = await _tagService.List();
            if (id == null)
            {
                // Create
                post = _mapper.Map<Post>(model);
                post.AuthorId = _userManager.GetUserId(User);
                post.TagPosts = model.GetTagPosts(tagList);
                if (string.IsNullOrWhiteSpace(post.Excerpt))
                {
                    var lineBreak = post.Content.IndexOf(Environment.NewLine, StringComparison.Ordinal);
                    if (lineBreak < 0)
                        lineBreak = post.Content.Length;
                    var length = Math.Min(lineBreak, 500);
                    var sub = post.Content.Substring(0, length);
                    post.Excerpt = Regex.Replace(sub, "<[^>]*(>|$)", "");
                }

                await _postService.Create(post);
            }
            else
            {
                // Update
                post = await _postService.GetById(id.Value);
                if (post.IsDraft)
                {
                    post.CreatedTime = DateTime.UtcNow;
                    post.ModifiedTime = null;
                }
                else
                {
                    post.ModifiedTime = DateTime.UtcNow;
                }

                _mapper.Map(model, post);
                post.TagPosts = model.GetTagPosts(tagList);

                await _postService.Update(post);
            }

            return RedirectToAction(nameof(Article), new { post.Slug });
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost("[action]/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var post = await _postService.GetById(id);
            await _postService.Delete(post);

            return RedirectToAction(nameof(Index));
        }

        [NonAction]
        public async Task<IActionResult> List(Func<Post, bool> predicate, int page, string title)
        {
            var user = User ?? _httpContextAccessor.HttpContext.User;
            if (!user.Identity.IsAuthenticated)
            {
                var oldPredicate = predicate;
                predicate = p => p.IsDraft == false && oldPredicate(p);
            }

            var list = await _postService.ListBy(p => predicate(p), page);

            if (page > 1)
            {
                if (!string.IsNullOrEmpty(title))
                    title += " ";
                title += $"Page {page}";
            }

            return View("/Views/Post/List.cshtml", new PostListViewModel { Title = title, List = list });
        }

        [ValidateAntiForgeryToken]
        [HttpPost("{slug}/comment")]
        public async Task<IActionResult> CreateComment(string slug, PostViewModel viewModel)
        {
            if (User.Identity.IsAuthenticated)
            {
                ModelState.Remove($"{nameof(PostViewModel.Comment)}.{nameof(PostViewModel.Comment.AuthorName)}");
                ModelState.Remove($"{nameof(PostViewModel.Comment)}.{nameof(PostViewModel.Comment.AuthorEmail)}");
            }

            if (!ModelState.IsValid)
            {
                viewModel.Post = await _postService.GetBySlug(slug);
                return View("Article", viewModel);
            }

            var comment = viewModel.Comment;
            var post = await _postService.GetBySlug(slug);
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.GetUserAsync(User);
                comment.RegisteredAuthor = user;
                comment.AuthorName = !string.IsNullOrEmpty(user.Name) ? user.Name : user.UserName;
                comment.AuthorEmail = user.Email;
            }

            post.Comments.Add(comment);
            await _postService.Update(post);

            return RedirectToAction(nameof(Article), new { slug });
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost("{slug}/comment/delete/{id}")]
        public async Task<IActionResult> DeleteComment(string slug, int id)
        {
            var post = await _postService.GetBySlug(slug);

            var comment = post.Comments.FirstOrDefault(c => c.Id == id);
            Guard.Against.NullThrow404NotFound(comment, nameof(comment));

            post.Comments.Remove(comment);
            await _postService.Update(post);

            return RedirectToAction(nameof(Article), new { slug });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [Route("/Error")]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/SimpleBlog/Controllers/TagController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleBlog.Services;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleBlog.Controllers
{
    [Route("t")]
    public class TagController : Controller
    {
        private readonly TagService _tagService;
        private readonly PostController _postController;

        public TagController(TagService tagService, PostController postController)
        {
            _tagService = tagService;
            _postController = postController;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string slug, [FromQuery(Name = "p")]int page = 1)
        {
            var list = await _tagService.List();
            return View(list);
        }

        [HttpGet("{slug}")]
        public async Task<IActionResult> PostList(string slug, [FromQuery(Name = "p")]int page = 1)
        {
            var tag = await _tagService.GetBySlug(slug);
            return await _postController.List(p => p.TagPosts.Any(tp => tp.TagId == tag.Id), page, tag.Name);
        }
    }
}

src/SimpleBlog/Views/Shared/List.cshtml
@model SimpleBlog.ViewModels.PostListViewModel
@{
    ViewData["Title"] = Model.Title;
}

@foreach (var item in Model.List)
{
    <div class="card mt-3">
        <div class="card-body">
            <a asp-controller="Post" asp-action="Article" asp-route-slug="@item.Slug">
                <h5 class="card-title">@Html.DisplayFor(m => item.Title)</h5>
            </a>
            <p class="card-text">
                <a class="btn btn-light btn-sm" asp-controller="Category" asp-action="Index" asp-route-slug="@item.Category.Slug">@Html.DisplayFor(m => item.Category.Name)</a>
                <small class="text-muted">
                    - <a href="#">@Html.DisplayFor(m => item.Author.UserName)</a>
                    - <time datetime="@item.CreatedTime.ToString("u")">@Html.DisplayFor(m => item.CreatedTime)</time>
                </small>
            </p>
            <p class="card-text">@Html.DisplayFor(m => item.Excerpt)</p>
        </div>
    </div>
}

<nav class="mt-4">
    <ul class="pagination justify-content-center">
        <li class="page-item"><a class="page-link" asp-route-p="1">&laquo;</a></li>
        <li class="page-item @(Model.List.HasPreviousPage ? "" : "disabled")">
            <a class="page-link px-3" asp-route-p="@(Model.List.PageIndex - 1)">&lsaquo;</a>
        </li>
        @for (var i = Math.Max(1, Model.List.PageIndex - 2); i < Model.List.PageIndex; i++)
        {
            <li class="page-item"><a class="page-link" asp-route-p="@i">@i</a></li>
        }
        <li class="page-item disabled"><a class="page-link">@Model.List.PageIndex</a></li>
        @for (var i = Model.List.PageIndex + 1; i <= Math.Min(Model.List.TotalPages, Model.List.PageIndex + 2); i++)
        {
            <li class="page-item"><a class="page-link" asp-route-p="@i">@i</a></li>
        }
        <li class="page-item @(Model.List.HasNextPage ? "" : "disabled")">
            <a class="page-link px-3" asp-route-p="@(Model.List.PageIndex + 1)">&rsaquo;</a>
        </li>
        <li class="page-item"><a class="page-link" asp-route-p="@Model.List.TotalPages">&raquo;</a></li>
    </ul>
</nav>

src/SimpleBlog/Views/Shared/_Layout.cshtml
@inject IOptionsSnapshot<Config> Config
@inject CategoryService CategoryService
@inject SignInManager<User> SignInManager
@{
    var categories = await CategoryService.List();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@(!string.IsNullOrEmpty(ViewData["Title"] as string) ? $"{ViewData["Title"]} - {Config.Value.SiteName}" : Config.Value.SiteName)</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Stylesheets", required: false)
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Post" asp-action="Index">@Config.Value.SiteName</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial" />
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown" href="#">Categories</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">All categories</a>
                            @if (categories.Any())
                            {
                                <div class="dropdown-divider"></div>
                                @foreach (var item in categories)
                                 {
                                     <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="PostList" asp-route-slug="@item.Slug">@Html.DisplayFor(m => item.Name)</a>
                                 }
                            }
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Tag" asp-action="Index">Tags</a>
                    </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="New">New post</a>
                        </li>
                    }
                    <form class="form-inline ml-auto" action="https://www.google.com/search" method="get" target="_blank">
                        <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <input name="sitesearch" type="hidden" value="@($"{Context.Request.Host}{Context.Request.PathBase}")">
                        <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy;@DateTime.Now.Year - @Config.Value.SiteName
    </div>
</footer>

<script src="~/lib/jquery/jquery.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)
</body>
</html>